# Generated by Django 4.1 on 2022-08-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_guestemail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestemail',
            name='active',
        ),
    ]
