# Generated by Django 4.1 on 2022-08-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
