# Generated by Django 4.1 on 2022-08-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Facturation'), ('shipping', 'Livraison')], max_length=120, verbose_name="Type d'adresse")),
                ('address_line_1', models.CharField(max_length=120, verbose_name='Adresse 1')),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Adresse 2')),
                ('country', models.CharField(blank=True, default='United States Of America', max_length=120, null=True, verbose_name='Pays')),
                ('city', models.CharField(max_length=120, verbose_name='Ville')),
                ('state', models.CharField(max_length=120, verbose_name='Etat')),
                ('postal_code', models.CharField(max_length=120, verbose_name='Code postale')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingprofile', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Adresses de livraison',
            },
        ),
    ]
