# Generated by Django 4.1 on 2022-08-25 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=150, verbose_name='N° de la commande')),
                ('status', models.CharField(choices=[('created', 'Créée'), ('paid', 'Payée'), ('shipped', 'Livrée'), ('refunded', 'Remboursée')], default='created', max_length=100)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=5.99, max_digits=100, verbose_name='Livraison')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Total')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Panier')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
