# Generated by Django 4.1 on 2022-08-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_shipping_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=100, verbose_name='Frais de livraison'),
        ),
    ]
