# Generated by Django 4.1 on 2022-08-25 10:48

import django.core.validators
from django.db import migrations, models
import products.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Article')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=100, validators=[django.core.validators.MaxValueValidator(1000000000000000000), django.core.validators.MinValueValidator(1)], verbose_name='Prix')),
                ('image', models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Image')),
                ('feature', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
