# Generated by Django 4.1 on 2022-08-25 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_stock_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=100, validators=[django.core.validators.MaxValueValidator(1000000000000000000), django.core.validators.MinValueValidator(1)], verbose_name='Prix unitaire'),
        ),
    ]
