# Generated by Django 4.1 on 2022-08-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_categorie_active'),
        ('products', '0007_product_stock_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='category.categorie', verbose_name='Catégories'),
        ),
    ]
